const disableArgs = {
    align: { table: { disable: true } },
    direction: { table: { disable: true } },
    backgroundColor: { table: { disable: true } },
    bottom: { table: { disable: true } },
    color: { table: { disable: true } },
    justify: { table: { disable: true } },
    gap: { table: { disable: true } },
    width: { table: { disable: true } },
    height: { table: { disable: true } },
    maxWidth: { table: { disable: true } },
    maxHeight: { table: { disable: true } },
    minWidth: { table: { disable: true } },
    minHeight: { table: { disable: true } },
    margin: { table: { disable: true } },
    marginTop: { table: { disable: true } },
    marginBottom: { table: { disable: true } },
    marginLeft: { table: { disable: true } },
    marginRight: { table: { disable: true } },
    padding: { table: { disable: true } },
    paddingTop: { table: { disable: true } },
    paddingBottom: { table: { disable: true } },
    paddingLeft: { table: { disable: true } },
    paddingRight: { table: { disable: true } },
    fontWeight: { table: { disable: true } },
    textAlign: { table: { disable: true } },
    fontSize: { table: { disable: true } },
    lineHeight: { table: { disable: true } },
    letterSpacing: { table: { disable: true } },
    textTransform: { table: { disable: true } },
    position: { table: { disable: true } },
    display: { table: { disable: true } },
    top: { table: { disable: true } },
    left: { table: { disable: true } },
    right: { table: { disable: true } },
    radius: { table: { disable: true } },
    as: { table: { disable: true } },
}

export default disableArgs;